USE [RabbitMQ]

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Email') 
BEGIN
	CREATE TABLE [dbo].[Email](
		[Id] [uniqueidentifier] NOT NULL,
		[PaymentId] [uniqueidentifier] NOT NULL,
		[Notified] [tinyint] NOT NULL,
		[CreationDate] [smalldatetime] NOT NULL,

	CONSTRAINT [PK_Email] PRIMARY KEY CLUSTERED([Id] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) 
	ON [PRIMARY]

	ALTER TABLE [dbo].[Email]  WITH CHECK ADD  CONSTRAINT [FK_Email_Payment] FOREIGN KEY([PaymentId])
	REFERENCES [dbo].[Payment] ([Id])

	ALTER TABLE [dbo].[Email] CHECK CONSTRAINT [FK_Email_Payment]
END